services:
  code-server-dev-nvidia:
    image: juniocalu/code-server-dev-ffplayout:v1.0
    container_name: code-server-dev-nvidia
    restart: always
    privileged: true
    stdin_open: true
    tty: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Maceio
      - PASSWORD=Tu9ushul8ein
      - HASHED_PASSWORD=
      - SUDO_PASSWORD=linux1234
      - SUDO_PASSWORD_HASH=
      - PROXY_DOMAIN=
      - DEFAULT_WORKSPACE=/config/workspace
      - VIDEO_GID=44
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    cap_add:
      - SYS_ADMIN
    volumes:
      - /var/lib/docker_code_server:/var/lib/docker
      - ./docker/code-server/config:/config
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro    
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      #- /opt/ssl:/opt/ssl:rw
      #- /dev/shm:/var/www/html/live:rw
      #- /usr/local/cuda:/usr/local/cuda:rw
    devices:
      - /dev/nvidia0
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-caps
      - /dev/nvidia-modeset
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "1942:1942"
      - "443:443"
      - "80:80"
      - "8787:8787"
      - "8443:8443"
      - "8082:8081"
      - "8080:8080"
      - "8181:8181"
      - "1935:1935"
      - "1936:1936"
      - "6000:6000/udp"
      - "9091:9091"
      - "8585:8083"
      - "1985:1985"
      - "5656:5656"
      - "5250:5250"
      - "9443:9443"
      - "8888:8888"
      - "8383:8383"
      - "8788:8788"
      - "3002:3002"
      - "3003:3003"
      - "3004:3004"
      - "3005:3005"
      - "3006:3006"
      - "3000:3000"
      - "3001:3001"
      - "8000:8000"
      - "8001:8001"
      - "5253:5253"
      - "554:554"
